export const REQUEST_POST = 'REQUEST_POST'

export const SUCCESS_GET_POSTS = 'SUCCESS_GET_POSTS'
export const ERROR_GET_POSTS = 'ERROR_GET_POSTS'

export const SUCCESS_CREATE_POST = 'SUCCESS_CREATE_POST'
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST'

export const SUCCESS_LIKE_POST = 'SUCCESS_LIKE_POST'
export const ERROR_LIKE_POST = 'ERROR_LIKE_POST'

export const SUCCESS_DISLIKE_POST = 'SUCCESS_DISLIKE_POST'
export const ERROR_DISLIKE_POST = 'ERROR_DISLIKE_POST'

export const SUCCESS_COMMENT_POST = 'SUCCESS_COMMENT_POST'
export const ERROR_COMMENT_POST = 'ERROR_COMMENT_POST'