export const REQUEST_POST = 'REQUEST_POST'

export const SUCCESS_GET_POSTS = 'SUCCESS_GET_POSTS'
export const ERROR_GET_POSTS = 'ERROR_GET_POSTS'

export const SUCCESS_GET_FEED_POSTS = 'SUCCESS_GET_FEED_POSTS'
export const ERROR_GET_FEED_POSTS = 'ERROR_GET_FEED_POSTS'

export const SUCCESS_CREATE_POST = 'SUCCESS_CREATE_POST'
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST'

export const SUCCESS_LIKE_POST = 'SUCCESS_LIKE_POST'
export const ERROR_LIKE_POST = 'ERROR_LIKE_POST'

export const SUCCESS_DISLIKE_POST = 'SUCCESS_DISLIKE_POST'
export const ERROR_DISLIKE_POST = 'ERROR_DISLIKE_POST'

export const SUCCESS_COMMENT_POST = 'SUCCESS_COMMENT_POST'
export const ERROR_COMMENT_POST = 'ERROR_COMMENT_POST'

export const SUCCESS_BOOKMARK_POST = 'SUCCESS_BOOKMARK_POST'
export const ERROR_BOOKMARK_POST = 'ERROR_BOOKMARK_POST'

export const SUCCESS_UNBOOKMARK_POST = 'SUCCESS_UNBOOKMARK_POST'
export const ERROR_UNBOOKMARK_POST = 'ERROR_UNBOOKMARK_POST'

export const SUCCESS_DELETE_POST = 'SUCCESS_DELETE_POST'
export const ERROR_DELETE_POST = 'ERROR_DELETE_POST'

/*-------------------------------------------------- user types ------------------------------------------------------*/

export const SUCCESS_FOLLOW_USER = 'SUCCESS_FOLLOW_USER'
export const ERROR_FOLLOW_USER = 'ERROR_FOLLOW_USER'
export const SUCCESS_UNFOLLOW_USER = 'SUCCESS_UNFOLLOW_USER'
export const ERROR_UNFOLLOW_USER = 'ERROR_UNFOLLOW_USER'